name: Build docker image

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Tag for this image build'
        required: true
        default: 'latest'

jobs:
  docker_build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Docker Prune
        run: docker system prune --all

      - name: Build docker image
        run: docker build --no-cache -t ghcr.io/horego/unraidDockerTest:${{ github.event.inputs.image_tag }} .

      - name: Push to github packages
        run: docker push ghcr.io/horego/unraidDockerTest:${{ github.event.inputs.image_tag }}